const countries = {
  "en-IN": "English",
  "hi-IN": "Hindi",
  "am-ET": "Amharic",
  "ar-SA": "Arabic",
  "be-BY": "Bielarus",
  "as-IN": "Assamese",
  "bn-IN": "Bangla",
  "brx-IN": "Bodo",
  "ccp-IN": "Chakma",
  "gu-IN": "Gujarati",
  "kn-IN": "Kannada",
  "ks-IN": "Kashmiri",
  "kok-IN": "Konkani",
  "ml-IN": "Malayalam",
  "mni-IN": "Manipuri",
  "mr-IN": "Marathi",
  "ne-IN": "Nepali",
  "or-IN": "Odia",
  "pa-IN": "Punjabi",
  "sa-IN	": "Sanskrit",
  "ta-IN": "Tamil",
  "te-IN": "Telugu",
  "ur-IN": "Urdu",
  "af": "Afrikaans", 
  "ak":  "Akan" ,
  "sq":  "Albanian", 
  "am":  "Amharic" , 
  "ar":  "Arabic" , 
  "hy":  "Armenian" , 
  "as":  "Assamese" , 
  "ay":  "Aymara" , 
  "az":  "Azerbaijani" , 
  "bm":  "Bambara" , 
  "eu":  "Basque" , 
  "be":  "Belarusian" , 
  "bn":  "Bengali" , 
  "bs":  "Bosnian" , 
  "bg":  "Bulgarian" , 
  "my":  "Burmese" , 
  "ca":  "Catalan; Valencian" , 
  "ny":  "Chichewa; Chewa; Nyanja" , 
  "zh":  "Chinese" , 
  "co":  "Corsican" , 
  "hr":  "Croatian" , 
  "cs":  "Czech" , 
  "da":  "Danish" , 
  "dv":  "Divehi; Dhivehi; Maldivian;" , 
  "nl":  "Dutch" , 
  // "en":  "English" , 
  "eo":  "Esperanto" , 
  "et":  "Estonian" , 
  "ee":  "Ewe" , 
  "fi":  "Finnish" , 
  "fr":  "French" , 
  "gl":  "Galician" , 
  "ka":  "Georgian" , 
  "de":  "German" , 
  "el":  "Greek, Modern" , 
  "gn":  "Guaraní" , 
  "gu":  "Gujarati" , 
  "ht":  "Haitian; Haitian Creole" , 
  "ha":  "Hausa" , 
  "he":  "Hebrew (modern)" , 
  // "hi-IN":  "Hindi" , 
  "hu":  "Hungarian" , 
  "id":  "Indonesian" , 
  "ga":  "Irish" , 
  "ig":  "Igbo" , 
  "is":  "Icelandic" , 
  "it":  "Italian" , 
  "ja":  "Japanese" , 
  "jv":  "Javanese" , 
  "kn":  "Kannada" , 
  "kk":  "Kazakh" , 
  "km":  "Khmer" , 
  "rw":  "Kinyarwanda" , 
  "ky":  "Kirghiz, Kyrgyz" , 
  "ko":  "Korean" , 
  "ku":  "Kurdish" , 
  "la":  "Latin" , 
  "lb":  "Luxembourgish, Letzeburgesch" , 
  "lg":  "Luganda" , 
  "ln":  "Lingala" , 
  "lo":  "Lao" , 
  "lt":  "Lithuanian" , 
  "lv":  "Latvian" , 
  "mk":  "Macedonian" , 
  "mg":  "Malagasy" , 
  "ms":  "Malay" , 
  "ml":  "Malayalam" , 
  "mt":  "Maltese" , 
  "mi":  "Māori" , 
  "mr":  "Marathi (Marāṭhī)" , 
  "mn":  "Mongolian" , 
  "ne":  "Nepali" , 
  "no":  "Norwegian" , 
  "om":  "Oromo" , 
  "or":  "Oriya" , 
  "pa":  "Panjabi, Punjabi" , 
  "fa":  "Persian" , 
  "pl":  "Polish" , 
  "ps":  "Pashto, Pushto" , 
  "pt":  "Portuguese" , 
  "qu":  "Quechua" , 
  "ro":  "Romanian, Moldavian, Moldovan" , 
  "ru":  "Russian" , 
  "sa":  "Sanskrit (Saṁskṛta)" , 
  "sd":  "Sindhi" , 
  "sm":  "Samoan" , 
  "sr":  "Serbian" , 
  "gd":  "Scottish Gaelic; Gaelic" , 
  "sn":  "Shona" , 
  "si":  "Sinhala, Sinhalese" , 
  "sk":  "Slovak" , 
  "sl":  "Slovene" , 
  "so":  "Somali" , 
  "st":  "Southern Sotho" , 
  "es":  "Spanish; Castilian" , 
  "su":  "Sundanese" , 
  "sw":  "Swahili" , 
  "sv":  "Swedish" , 
  "ta":  "Tamil" , 
  "te":  "Telugu" , 
  "tg":  "Tajik" , 
  "th":  "Thai" , 
  "ti":  "Tigrinya" , 
  "tk":  "Turkmen" , 
  "tl":  "Tagalog" , 
  "tr":  "Turkish" , 
  "ts":  "Tsonga" , 
  "tt":  "Tatar" , 
  "ug":  "Uighur, Uyghur" , 
  "uk":  "Ukrainian" , 
  "ur":  "Urdu" , 
  "uz":  "Uzbek" , 
  "vi":  "Vietnamese" , 
  "cy":  "Welsh" , 
  "fy":  "Western Frisian" , 
  "xh":  "Xhosa" , 
  "yi":  "Yiddish" , 
  "yo":  "Yoruba"  
}
export default countries;
